# Change these first
owner: silkkycloud # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

assignees:
  - TheSilkky

sites:
  - name: Website
    url: https://www.silkky.cloud
  - name: Piped
    url: https://piped.silkky.cloud
  - name: Piped Proxy
    url: https://proxy.piped.silkky.cloud
  - name: Piped API
    url: https://api.piped.silkky.cloud/trending
  - name: Pleroma
    url: https://social.silkky.cloud
  - name: Pleroma Proxy
    url: https://proxy.social.silkky.cloud
  - name: Searx
    url: https://searx.silkky.cloud
  - name: Send
    url: https://send.silkky.cloud
  - name: Vikunja
    url: tasks.silkky.cloud
  - name: Bitwarden
    url: https://vault.silkky.cloud
  - name: Libreddit
    url: libreddit.silkky.cloud
  - name: Nitter
    url: https://nitter.silkky.cloud
  - name: Privatebin
    url: https://privatebin.silkky.cloud
  - name: Server 1
    check: "tcp-ping"
    url: $SERVER1_IP
    port: 80
  - name: Server 2
    check: "tcp-ping"
    url: $SERVER2_IP
    port: 80
  - name: Server 3
    check: "tcp-ping"
    url: $SERVER3_IP
    port: 80

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.silkky.cloud
  #baseUrl: /status
  favicon: https://www.silkky.cloud/img/favicons/favicon-32x32.png
  theme: dark
  name: Silkky.Cloud Status
  introTitle: "**Silkky.Cloud Status** is our service uptime monitoring page."
  navbar:
    - title: Status
      href: /
    - title: Silkky.Cloud
      href: https://www.silkky.cloud
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
